basePath: /api
definitions:
  user.ProfileDto:
    properties:
      email:
        example: test@test.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Wick
        type: string
    type: object
  user.SignInDto:
    properties:
      email:
        example: test@test.com
        type: string
      password:
        example: test123
        type: string
    type: object
  user.SignUpDto:
    properties:
      email:
        example: test@test.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Wick
        type: string
      password:
        example: test123
        type: string
    type: object
  user.TokenDto:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: Swagger for Shop Api
  title: Shop Api
  version: "1.0"
paths:
  /users/me:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ProfileDto'
      summary: Get my profile
      tags:
      - users
  /users/signin:
    post:
      parameters:
      - description: User details for login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.SignInDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.TokenDto'
      summary: Sign in
      tags:
      - users
  /users/signup:
    post:
      parameters:
      - description: User details for registration
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.SignUpDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.TokenDto'
      summary: Sign Up
      tags:
      - users
swagger: "2.0"
