basePath: /api
definitions:
  db.Role:
    enum:
    - member
    - admin
    type: string
    x-enum-varnames:
    - RoleMember
    - RoleAdmin
  db.StripeStatus:
    enum:
    - pending
    - succeeded
    - failed
    - canceled
    - refunded
    type: string
    x-enum-varnames:
    - StripeStatusPending
    - StripeStatusSucceeded
    - StripeStatusFailed
    - StripeStatusCanceled
    - StripeStatusRefunded
  product.CreateProductDto:
    properties:
      description:
        type: string
      discount:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  product.ProductDto:
    properties:
      description:
        type: string
      discount:
        type: integer
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  product.ProductsPaginationDto:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      products:
        items:
          $ref: '#/definitions/product.ProductDto'
        type: array
      total:
        type: integer
    type: object
  receipt.CreateReceiptDto:
    properties:
      products:
        additionalProperties:
          format: int32
          type: integer
        type: object
    type: object
  receipt.ReceiptDto:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      products:
        items:
          $ref: '#/definitions/receipt.ReceiptProductDto'
        type: array
      stripeId:
        type: string
      stripeStatus:
        $ref: '#/definitions/db.StripeStatus'
      sumDiscount:
        type: integer
      sumPrice:
        type: integer
    type: object
  receipt.ReceiptProductDto:
    properties:
      discount:
        type: integer
      name:
        type: string
      price:
        type: integer
      productId:
        type: integer
      quantity:
        type: integer
    type: object
  receipt.ReceiptsPaginationDto:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      receipts:
        items:
          $ref: '#/definitions/receipt.ReceiptDto'
        type: array
      total:
        type: integer
    type: object
  user.ProfileDto:
    properties:
      createdAt:
        type: string
      email:
        example: test@test.com
        type: string
      firstName:
        example: John
        type: string
      id:
        format: int64
        type: integer
      lastName:
        example: Wick
        type: string
      userRole:
        allOf:
        - $ref: '#/definitions/db.Role'
        example: member
    type: object
  user.SignInDto:
    properties:
      email:
        example: test@test.com
        type: string
      password:
        example: test123
        type: string
    type: object
  user.SignUpDto:
    properties:
      email:
        example: test@test.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Wick
        type: string
      password:
        example: test123
        type: string
    type: object
  user.TokenDto:
    properties:
      token:
        type: string
    type: object
  user.UsersPaginationDto:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
      users:
        items:
          $ref: '#/definitions/user.ProfileDto'
        type: array
    type: object
info:
  contact: {}
  description: Swagger for Shop Api
  title: Shop Api
  version: "1.0"
paths:
  /payment/cancel:
    get:
      parameters:
      - description: Session ID
        in: query
        name: sessionId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/receipt.ReceiptDto'
      security:
      - ApiKeyAuth: []
      summary: Cancel Payment
      tags:
      - payment
  /payment/create:
    post:
      parameters:
      - description: Payment details
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/receipt.CreateReceiptDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/receipt.ReceiptDto'
      security:
      - ApiKeyAuth: []
      summary: Create Payment
      tags:
      - payment
  /payment/get:
    get:
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/receipt.ReceiptsPaginationDto'
      security:
      - ApiKeyAuth: []
      summary: Get Receipts
      tags:
      - payment
  /payment/success:
    get:
      parameters:
      - description: Session ID
        in: query
        name: sessionId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/receipt.ReceiptDto'
      security:
      - ApiKeyAuth: []
      summary: Success Payment
      tags:
      - payment
  /products/create:
    post:
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.CreateProductDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductDto'
      security:
      - ApiKeyAuth: []
      summary: Create Product
      tags:
      - products
  /products/get:
    get:
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductsPaginationDto'
      security:
      - ApiKeyAuth: []
      summary: Get Products
      tags:
      - products
  /users/get:
    get:
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UsersPaginationDto'
      security:
      - ApiKeyAuth: []
      summary: Get my profile
      tags:
      - users
  /users/me:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ProfileDto'
      security:
      - ApiKeyAuth: []
      summary: Get my profile
      tags:
      - users
  /users/signin:
    post:
      parameters:
      - description: User details for login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.SignInDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.TokenDto'
      summary: Sign in
      tags:
      - users
  /users/signup:
    post:
      parameters:
      - description: User details for registration
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.SignUpDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.TokenDto'
      summary: Sign Up
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" followed by a space and then your token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
